chore: bump web3-functions-sdk
gelatodigital/web3-functions-template pull request #27
Opened 2023-07-18 06:55 UTC by brandonchuah

2023-07-18 13:45 UTC, mkykadir approved these changes

2023-07-18 14:04 UTC, goums requested changes

2023-07-18 14:04 UTC, goums commented on package.json
>      "ethers": "^5.7.1",
let's remove `ethers` dependency and only use the one we actually use

2023-07-19 04:56 UTC, brandonchuah commented on package.json
>      "ethers": "^5.7.1",
Replaced ethers in most scripts as well. But keeping the dependency for private w3f.

2023-07-19 05:00 UTC, goums approved these changes

2023-07-19 05:02 UTC, merged